### ISSUE TITLE
NVidia Mie approximation alpha calculation

### ISSUE THREAD

**Issue by BadMachine** [Sunset-Flock/Timberdoodle#4]
Hey everyone.
Isnt it an error in the hg_draine_phase function (alpha calculation) ?
https://github.com/Sunset-Flock/Timberdoodle/blob/223851b27333616779c09e8578a6a03a73f10a5c/src/rendering/tasks/sky.hlsl#L98
I assume you are using the model for the large droplet diameter:
![image](https://github.com/user-attachments/assets/e0cbb621-5482-4fc1-91d5-959d9a548bfd)

Meanwhile in your implementation its:
`
 const float alpha = exp(3.62489 - (0.599085 / (diameter + 5.52825)));
`

**Comment by BadMachine** [comment]
Also in your code you use particle size of 3.6
`
const float mie_phase_value = hg_draine_phase(cos_theta, 3.6);
`
When original model proposes the parametisation for particles 5 < d < 50.
Is it a kinda fine-tuned constant ?

**Comment by MatejSakmary** [comment]
Thank you, good catch! I merged it in.
